### ISSUE TITLE
How to add servers?

### ISSUE THREAD

**Issue by itJunky** [CCrypto/ccvpn3#5]
How to add servers?
Can't find it in admin panel.

When i getting vpn.config i see `remote gw.random.204vpn.net 1196 udp` what is this and how i can change it?
How i can configure my own vpn server and how add certificates to panel ccvpn?

**Comment by 0xa** [comment]
Servers and sessions are queried from lambdacore, a still proprietary API. If you want to use it you would need to either:
- use lambdacore (either as a service or by buying a license);
- reimplement a compatible API (there are only a few endpoints needed);
- fork and replace the parts using lambdacore.

**Comment by itJunky** [comment]
O no, it's so hard for peoples. I think better for me is using another product like https://pritunl.com/

**Comment by Cubox-** [comment]
Hello itJunky.

Thanks for your interest in our project, the reason we publish and keep an organised and documented repository is to share how our service works.
This effort has many reasons, such as having our customers be able to check the source code that runs their accounts, and their VPN connections. We also like to give back to the open source community that we use and love. There are many others reasons I cannot list here.

However, this repository is not meant as a "plug and play" solution. We never intended building this code that anyone would be using it unedited. If the documentation is lacking, or incorrect, you are welcome to help us correct it. However this is not meant to be used to the untrained eye.

Thanks for understanding. Feel free to drop an email if you want to chat a bit more cubox@cubox.me

**Comment by Cubox-** [comment]
Fixed by https://github.com/CCrypto/ccvpn3/commit/98b41e144eb0526f39ed9c13d52ae98329b74439
